; [env:esp01_1m]
; platform = espressif8266
; board = esp01_1m
; build_flags = -DESP8266 -DIRLED=3
; monitor_speed = 115200
; framework = arduino
; lib_ldf_mode = deep+
; lib_deps =
;     ArduinoJson
;     ESP8266WiFi
;     ;fauxmoESP
;     vintlabs/FauxmoESP@3.4
;     IRremoteESP8266
;     ;ArduinoOTA
;     ;ESP8266mDNS
;     ;ESP8266WebServer
;     ;ESP8266HTTPUpdateServer
;     tzapu/WiFiManager@^2.0.17
; build_src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/> -<**/*.backup> ; + is include, - is exclude folders or extensions
; extra_scripts = post:./scripts/upload_script.py

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
build_flags = -DESP8266 -DIRLED=4 -O3
monitor_speed = 115200
framework = arduino
lib_ldf_mode = deep+
lib_deps =
    ArduinoJson
    ;fauxmoESP
    vintlabs/FauxmoESP@3.4
    IRremoteESP8266
    ;ArduinoOTA
    ESP8266mDNS
    ;ESP8266WebServer
    ;ESP8266HTTPUpdateServer
    tzapu/WiFiManager@^2.0.17
    me-no-dev/ESPAsyncTCP@^2.0.0
build_src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/> -<**/*.backup> ; + is include, - is exclude folders or extensions
extra_scripts = post:./scripts/upload_script.py

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; build_flags = -DESP32 -DIRLED=4 -Wno-return-type
; monitor_speed = 115200
; framework = arduino
; lib_ldf_mode = deep+
; lib_deps =
;     ArduinoJson
;     WiFi
;     vintlabs/FauxmoESP@3.4
;     IRremoteESP8266
;     ;ArduinoOTA
;     ;ESP32Ping
;     ;HTTPUpdateServer
;     me-no-dev/AsyncTCP@^3.3.2
;     ;ESPmDNS
;     tzapu/WiFiManager@^2.0.17
; build_src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/> -<backup/> -<**/*.backup> ; + is include, - is exclude folders or extensions
; extra_scripts = post:./scripts/upload_script.py